IPv4 location markup
Samsung/CredData pull request #101
Opened 2024-03-12 11:46 UTC by Yullia

2024-03-12 12:41 UTC, babenek requested changes
add Info to skip the obfuscation
 '214.293.362.630' - becomes not an IP

2024-03-12 13:42 UTC, Yullia commented on meta/7f0408de.csv
> +132046,abfe0f70,GitHub,7f0408de,data/7f0408de/other/abfe0f70.md,567:567,T,F,7,19,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132045,abfe0f70,GitHub,7f0408de,data/7f0408de/other/abfe0f70.md,564:564,T,F,7,19,F,F,,,Info,,0.00,,F,F,F,Other
132046,abfe0f70,GitHub,7f0408de,data/7f0408de/other/abfe0f70.md,567:567,T,F,7,19,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:43 UTC, Yullia commented on meta/7f0408de.csv
> +132057,e15fd91c,GitHub,7f0408de,data/7f0408de/other/e15fd91c.md,50:50,T,F,18,30,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132050,67e9fdda,GitHub,7f0408de,data/7f0408de/other/67e9fdda.md,103:103,T,F,75,85,F,F,,,Info,,0.00,,F,F,F,Other
132051,67e9fdda,GitHub,7f0408de,data/7f0408de/other/67e9fdda.md,104:104,T,F,90,100,F,F,,,Info,,0.00,,F,F,F,Other
132052,67e9fdda,GitHub,7f0408de,data/7f0408de/other/67e9fdda.md,105:105,T,F,75,85,F,F,,,Info,,0.00,,F,F,F,Other
132053,67e9fdda,GitHub,7f0408de,data/7f0408de/other/67e9fdda.md,106:106,T,F,75,85,F,F,,,Info,,0.00,,F,F,F,Other
132054,67e9fdda,GitHub,7f0408de,data/7f0408de/other/67e9fdda.md,107:107,T,F,90,100,F,F,,,Info,,0.00,,F,F,F,Other
132055,67e9fdda,GitHub,7f0408de,data/7f0408de/other/67e9fdda.md,138:138,T,F,133,146,F,F,,,Info,,0.00,,F,F,F,Other
132056,6e0df309,GitHub,7f0408de,data/7f0408de/other/6e0df309.md,29:29,T,F,10,21,F,F,,,Info,,0.00,,F,F,F,Other
132057,e15fd91c,GitHub,7f0408de,data/7f0408de/other/e15fd91c.md,50:50,T,F,18,30,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:43 UTC, Yullia commented on meta/7f0408de.csv
> +132069,a75844c1,GitHub,7f0408de,data/7f0408de/other/a75844c1.md,245:245,T,F,24,37,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132060,75641abb,GitHub,7f0408de,data/7f0408de/other/75641abb.md,8:8,T,F,5,20,F,F,,,Info,,0.00,,F,F,F,Other
132061,75641abb,GitHub,7f0408de,data/7f0408de/other/75641abb.md,26:26,T,F,36,51,F,F,,,Info,,0.00,,F,F,F,Other
132062,75641abb,GitHub,7f0408de,data/7f0408de/other/75641abb.md,123:123,T,F,35,50,F,F,,,Info,,0.00,,F,F,F,Other
132063,75641abb,GitHub,7f0408de,data/7f0408de/other/75641abb.md,191:191,T,F,16,31,F,F,,,Info,,0.00,,F,F,F,Other
132064,b1680fcb,GitHub,7f0408de,data/7f0408de/other/b1680fcb.md,188:188,T,F,13,27,F,F,,,Info,,0.00,,F,F,F,Other
132065,b1680fcb,GitHub,7f0408de,data/7f0408de/other/b1680fcb.md,194:194,T,F,13,27,F,F,,,Info,,0.00,,F,F,F,Other
132066,b1680fcb,GitHub,7f0408de,data/7f0408de/other/b1680fcb.md,202:202,T,F,13,27,F,F,,,Info,,0.00,,F,F,F,Other
132067,b1680fcb,GitHub,7f0408de,data/7f0408de/other/b1680fcb.md,206:206,T,F,13,27,F,F,,,Info,,0.00,,F,F,F,Other
132068,b1680fcb,GitHub,7f0408de,data/7f0408de/other/b1680fcb.md,207:207,T,F,15,29,F,F,,,Info,,0.00,,F,F,F,Other
132069,a75844c1,GitHub,7f0408de,data/7f0408de/other/a75844c1.md,245:245,T,F,24,37,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:44 UTC, Yullia commented on meta/7f0408de.csv
> +132072,ca04bea7,GitHub,7f0408de,data/7f0408de/test/ca04bea7.md,228:228,T,F,59,72,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132072,ca04bea7,GitHub,7f0408de,data/7f0408de/test/ca04bea7.md,228:228,T,F,59,72,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:44 UTC, Yullia commented on meta/81cd05d0.csv
> +132089,02fd2d8d,GitHub,81cd05d0,data/81cd05d0/src/02fd2d8d.json,916970:916970,T,F,14,25,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132086,02fd2d8d,GitHub,81cd05d0,data/81cd05d0/src/02fd2d8d.json,914185:914185,T,F,14,22,F,F,,,Info,,0.00,,F,F,F,Other
132087,02fd2d8d,GitHub,81cd05d0,data/81cd05d0/src/02fd2d8d.json,914192:914192,T,F,15,23,F,F,,,Info,,0.00,,F,F,F,Other
132088,02fd2d8d,GitHub,81cd05d0,data/81cd05d0/src/02fd2d8d.json,915178:915178,T,F,15,23,F,F,,,Info,,0.00,,F,F,F,Other
132089,02fd2d8d,GitHub,81cd05d0,data/81cd05d0/src/02fd2d8d.json,916970:916970,T,F,14,25,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:45 UTC, Yullia commented on meta/850c2319.csv
> +132095,f6959391,GitHub,850c2319,data/850c2319/test/f6959391.go,618:618,T,F,31,38,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132092,f6959391,GitHub,850c2319,data/850c2319/test/f6959391.go,615:615,T,F,35,42,F,F,,,Info,,0.00,,F,F,F,Other
132093,f6959391,GitHub,850c2319,data/850c2319/test/f6959391.go,616:616,T,F,20,27,F,F,,,Info,,0.00,,F,F,F,Other
132094,f6959391,GitHub,850c2319,data/850c2319/test/f6959391.go,617:617,T,F,37,44,F,F,,,Info,,0.00,,F,F,F,Other
132095,f6959391,GitHub,850c2319,data/850c2319/test/f6959391.go,618:618,T,F,31,38,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:45 UTC, Yullia commented on meta/894e3377.csv
> +132148,b679985c,GitHub,894e3377,data/894e3377/test/b679985c.php,236:236,T,F,92,107,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132148,b679985c,GitHub,894e3377,data/894e3377/test/b679985c.php,236:236,T,F,92,107,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:45 UTC, Yullia commented on meta/8c9b3ae9.csv
> +132150,bca40d89,GitHub,8c9b3ae9,data/8c9b3ae9/src/bca40d89.properties,2:2,T,F,35,48,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132150,bca40d89,GitHub,8c9b3ae9,data/8c9b3ae9/src/bca40d89.properties,2:2,T,F,35,48,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:45 UTC, Yullia commented on meta/8d217d6c.csv
> +132151,7173d869,GitHub,8d217d6c,data/8d217d6c/src/7173d869.php,39:39,T,F,14,23,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132151,7173d869,GitHub,8d217d6c,data/8d217d6c/src/7173d869.php,39:39,T,F,14,23,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:45 UTC, Yullia commented on meta/9128de73.csv
> +132152,11563907,GitHub,9128de73,data/9128de73/other/11563907.md,76:76,T,F,135,146,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132152,11563907,GitHub,9128de73,data/9128de73/other/11563907.md,76:76,T,F,135,146,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 13:46 UTC, Yullia commented on meta/9d90ba70.csv
> +1635,1cc3b783,GitHub,9d90ba70,data/9d90ba70/src/1cc3b783.rst,1610:1610,T,F,49,56,F,F,,,,,0,0,F,F,F,Other
```suggestion
1635,1cc3b783,GitHub,9d90ba70,data/9d90ba70/src/1cc3b783.rst,1610:1610,T,F,49,56,F,F,,,Info,,0,0,F,F,F,Other
```

2024-03-12 13:46 UTC, Yullia commented on meta/a09d9e50.csv
> +6970,054074fe,GitHub,a09d9e50,data/a09d9e50/test/054074fe.ndjson,3609:3609,T,F,500,513,F,F,,,,,0,0,F,F,F,Other
```suggestion
6970,054074fe,GitHub,a09d9e50,data/a09d9e50/test/054074fe.ndjson,3609:3609,T,F,500,513,F,F,,,Info,,0,0,F,F,F,Other
```

2024-03-12 13:47 UTC, Yullia commented on meta/a09d9e50.csv
> +132162,054074fe,GitHub,a09d9e50,data/a09d9e50/test/054074fe.ndjson,828:828,T,F,1508,1515,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132159,054074fe,GitHub,a09d9e50,data/a09d9e50/test/054074fe.ndjson,401:401,T,F,211,225,F,F,,,Info,,0.00,,F,F,F,Other
132160,054074fe,GitHub,a09d9e50,data/a09d9e50/test/054074fe.ndjson,559:559,T,F,220,227,F,F,,,Info,,0.00,,F,F,F,Other
132161,054074fe,GitHub,a09d9e50,data/a09d9e50/test/054074fe.ndjson,692:692,T,F,279,289,F,F,,,Info,,0.00,,F,F,F,Other
132162,054074fe,GitHub,a09d9e50,data/a09d9e50/test/054074fe.ndjson,828:828,T,F,1508,1515,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-14 07:24 UTC, iuriimet approved these changes

2024-03-14 07:26 UTC, merged