IPv4 location markup batch 3
Samsung/CredData pull request #103
Opened 2024-03-12 12:12 UTC by Yullia

IPv4 location markup batch 3 (100-150)

2024-03-12 15:23 UTC, babenek requested changes
use Info for an IP address markup (TRUE - mandatory, FALSE - not necessary)

2024-03-12 17:08 UTC, Yullia commented on meta/894e3377.csv
> +132131,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,386:386,F,F,34,43,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132129,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,384:384,F,F,28,37,F,F,,,Info,,0.00,,F,F,F,Other
132130,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,385:385,F,F,30,39,F,F,,,Info,,0.00,,F,F,F,Other
132131,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,386:386,F,F,34,43,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 17:10 UTC, Yullia commented on meta/894e3377.csv
> +132147,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2569:2569,F,F,5,12,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132133,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,395:395,F,F,29,38,F,F,,,Info,,0.00,,F,F,F,Other
132134,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,396:396,F,F,24,33,F,F,,,Info,,0.00,,F,F,F,Other
132135,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,399:399,F,F,22,31,F,F,,,Info,,0.00,,F,F,F,Other
132136,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,400:400,F,F,37,46,F,F,,,Info,,0.00,,F,F,F,Other
132137,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,401:401,F,F,30,39,F,F,,,Info,,0.00,,F,F,F,Other
132138,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,402:402,F,F,23,32,F,F,,,Info,,0.00,,F,F,F,Other
132139,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,403:403,F,F,30,39,F,F,,,Info,,0.00,,F,F,F,Other
132140,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,404:404,F,F,32,41,F,F,,,Info,,0.00,,F,F,F,Other
132141,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,409:409,F,F,27,36,F,F,,,Info,,0.00,,F,F,F,Other
132142,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,435:435,F,F,17,28,F,F,,,Info,,0.00,,F,F,F,Other
132143,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,436:436,F,F,15,26,F,F,,,Info,,0.00,,F,F,F,Other
132144,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2566:2566,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
132145,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2567:2567,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
132146,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2568:2568,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
132147,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2569:2569,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 17:11 UTC, Yullia commented on meta/894e3377.csv
> +132147,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2569:2569,F,F,5,12,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132133,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,395:395,F,F,29,38,F,F,,,Info,,0.00,,F,F,F,Other
132134,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,396:396,F,F,24,33,F,F,,,Info,,0.00,,F,F,F,Other
132135,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,399:399,F,F,22,31,F,F,,,Info,,0.00,,F,F,F,Other
132136,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,400:400,F,F,37,46,F,F,,,Info,,0.00,,F,F,F,Other
132137,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,401:401,F,F,30,39,F,F,,,Info,,0.00,,F,F,F,Other
132138,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,402:402,F,F,23,32,F,F,,,Info,,0.00,,F,F,F,Other
132139,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,403:403,F,F,30,39,F,F,,,Info,,0.00,,F,F,F,Other
132140,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,404:404,F,F,32,41,F,F,,,Info,,0.00,,F,F,F,Other
132141,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,409:409,F,F,27,36,F,F,,,Info,,0.00,,F,F,F,Other
132142,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,435:435,F,F,17,28,F,F,,,Info,,0.00,,F,F,F,Other
132143,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,436:436,F,F,15,26,F,F,,,Info,,0.00,,F,F,F,Other
132144,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2566:2566,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
132145,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2567:2567,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
132146,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2568:2568,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
132147,ed108d6d,GitHub,894e3377,data/894e3377/src/ed108d6d.php,2569:2569,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 17:12 UTC, Yullia commented on meta/99f9a6ea.csv
> +132153,06572a96,GitHub,99f9a6ea,data/99f9a6ea/other/06572a96.md,283:283,F,F,0,7,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132153,06572a96,GitHub,99f9a6ea,data/99f9a6ea/other/06572a96.md,283:283,F,F,0,7,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 17:12 UTC, Yullia commented on meta/a0cd6261.csv
> +3786,1282093a,GitHub,a0cd6261,data/a0cd6261/src/1282093a.txt,28:28,T,F,36,50,F,F,,,,,0,0,F,F,F,Other
```suggestion
3784,1282093a,GitHub,a0cd6261,data/a0cd6261/src/1282093a.txt,42:42,T,F,36,50,F,F,,,Info,,0,0,F,F,F,Other
3785,1282093a,GitHub,a0cd6261,data/a0cd6261/src/1282093a.txt,31:31,T,F,36,50,F,F,,,Info,,0,0,F,F,F,Other
3786,1282093a,GitHub,a0cd6261,data/a0cd6261/src/1282093a.txt,28:28,T,F,36,50,F,F,,,Info,,0,0,F,F,F,Other
```

2024-03-12 17:13 UTC, Yullia commented on meta/a0cd6261.csv
> +6868,dbef751c,GitHub,a0cd6261,data/a0cd6261/other/dbef751c.md,94:94,F,F,13,22,F,F,,,,,0,0,F,F,F,Password
```suggestion
6867,dbef751c,GitHub,a0cd6261,data/a0cd6261/other/dbef751c.md,96:96,F,F,13,22,F,F,,,Info,,0,0,F,F,F,Password
6868,dbef751c,GitHub,a0cd6261,data/a0cd6261/other/dbef751c.md,94:94,F,F,13,22,F,F,,,Info,,0,0,F,F,F,Password
```

2024-03-12 17:14 UTC, Yullia commented on meta/a0cd6261.csv
> +132172,e955e6ae,GitHub,a0cd6261,data/a0cd6261/other/e955e6ae.md,1010:1010,T,F,42,49,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132169,d73e7ecc,GitHub,a0cd6261,data/a0cd6261/other/d73e7ecc.md,86:86,T,F,32,45,F,F,,,Info,,0.00,,F,F,F,Other
132170,d73e7ecc,GitHub,a0cd6261,data/a0cd6261/other/d73e7ecc.md,88:88,T,F,11,24,F,F,,,Info,,0.00,,F,F,F,Other
132171,7f6a3252,GitHub,a0cd6261,data/a0cd6261/other/7f6a3252.md,134:134,T,F,31,38,F,F,,,Info,,0.00,,F,F,F,Other
132172,e955e6ae,GitHub,a0cd6261,data/a0cd6261/other/e955e6ae.md,1010:1010,T,F,42,49,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 17:14 UTC, Yullia commented on meta/a0cd6261.csv
> +132186,3b98604a,GitHub,a0cd6261,data/a0cd6261/other/3b98604a.md,1704:1704,T,F,48,55,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132174,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,193:193,F,F,10,17,F,F,,,Info,,0.00,,F,F,F,Other
132175,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,194:194,F,F,22,29,F,F,,,Info,,0.00,,F,F,F,Other
132176,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,195:195,F,F,9,16,F,F,,,Info,,0.00,,F,F,F,Other
132177,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,249:249,T,F,30,37,F,F,,,Info,,0.00,,F,F,F,Other
132178,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,250:250,T,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
132179,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,742:742,T,F,7,18,F,F,,,Info,,0.00,,F,F,F,Other
132180,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,743:743,T,F,7,18,F,F,,,Info,,0.00,,F,F,F,Other
132181,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,744:744,T,F,7,18,F,F,,,Info,,0.00,,F,F,F,Other
132182,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,745:745,T,F,7,18,F,F,,,Info,,0.00,,F,F,F,Other
132183,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,751:751,T,F,7,22,F,F,,,Info,,0.00,,F,F,F,Other
132184,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,752:752,T,F,7,22,F,F,,,Info,,0.00,,F,F,F,Other
132185,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,753:753,T,F,7,22,F,F,,,Info,,0.00,,F,F,F,Other
132186,3b98604a,GitHub,a0cd6261,data/a0cd6261/other/3b98604a.md,1704:1704,T,F,48,55,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-12 17:57 UTC, Yullia commented on meta/a0cd6261.csv
> +132178,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,250:250,T,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
```suggestion
132178,b0464027,GitHub,a0cd6261,data/a0cd6261/other/b0464027.md,250:250,F,F,5,12,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-13 05:26 UTC, babenek submitted a review, later dismissed
LGTM

2024-03-14 07:22 UTC, iuriimet submitted a review, later dismissed

2024-03-18 16:10 UTC, babenek commented on meta/894e3377.csv
> +132148,b679985c,GitHub,894e3377,data/894e3377/test/b679985c.php,236:236,T,F,,,F,F,,,,,0.00,,F,F,F,Other
```suggestion
132148,b679985c,GitHub,894e3377,data/894e3377/test/b679985c.php,236:236,T,F,92,107,F,F,,,Info,,0.00,,F,F,F,Other
```

2024-03-18 16:39 UTC, babenek approved these changes
LGTM

2024-03-19 07:21 UTC, iuriimet approved these changes

2024-03-19 07:23 UTC, merged